In [157]:
from google.colab import drive
drive.mount('/content/drive')
import tensorflow as tf
from tensorflow import keras 
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import cv2
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import RandomizedSearchCV
import seaborn as sns
import random
import copy

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [67]:
X = np.array([
    [2,4],
      [2,6],
     [5, 6],
     [4,7],
     [8,3],
     [6,6],
     [5, 2],
     [5, 7],
     [6, 3],
     [4, 4]
   
])

C = np.array([
    [1,5],
     [4, 1],
     [8, 4]
])




In [170]:
class Kmeans:

    '''Implementing Kmeans algorithm.'''

    def __init__(self, n_clusters, epochs=100):
        self.n_clusters = n_clusters
        self.epochs = epochs
        self.centroids = np.array([])

    def _initalize_centriods(self, features):
      centriods = []
      for elem in range(self.n_clusters):
        centriods.append(np.random.rand(features.shape[1]))

      return np.array(centriods)

    def _compute_distance(self, features, centriods):
      return self._euclidean(features, centriods)
     


    def _compute_new_centroids(self, features, labels):
      unique_values, counts = np.unique(labels, return_counts=True)
      #print("Unique values : ", unique_values, "cOUNTS: ", counts)
      new_centroids = []

      for i, value in enumerate(unique_values):
        #print(i, value)
        centroid = 0
        for j, label in enumerate(labels):
         # print(j, label)
          if value == label:
            centroid += features[j] 
        new_centroids.append(centroid/ counts[i])


      return np.array(new_centroids)
        
       

    def get_closest_cluster(self, distance):
      return np.argmin(distance, axis=1)

    def train(self, features):
      self.centroids = self._initalize_centriods(features)
      self.centroids = C
      #print(".self.centroids", self.centroids)
      for i in range(self.epochs):
        old_centroids =  copy.deepcopy(self.centroids)
        c_distances = self._euclidean(features, old_centroids)
        current_labels = self.get_closest_cluster(c_distances)
        self.centroids = self._compute_new_centroids(features, current_labels)
        # print("new : ", self.centroids)
        # print("old : ", old_centroids)
        # print("equal", np.array_equal(self.centroids, old_centroids))
        if np.array_equal(self.centroids, old_centroids):
          return i, self.n_clusters, c_distances, current_labels, self.centroids 
        # else:
        #   self.centriods = new_centroids
      
        

    def _euclidean(self, features, centroids):
      #print("features: ", features)
      #print("centroids", centroids)
      distances = []
      for x in features:
        centroid_distance = []
        for c in centroids:
          distance = 0
          for i in range(len(x)):
             if isinstance(x[i], str) and isinstance(c[i], str):
                 if x[i] != c[i]:
                    distance += 1
             else:
               distance += pow((x[i] - c[i]), 2)
          centroid_distance.append(pow(distance, 1/2))
        distances.append(np.array(centroid_distance))

      return distances
    

In [171]:
km = Kmeans(3)

In [172]:
km.train(X)

([array([1.        , 3.88104367, 3.90512484]),
  array([1.        , 4.80234318, 3.04138127]),
  array([3.16227766, 3.09232922, 0.5       ]),
  array([2.82842712, 4.3660623 , 1.11803399]),
  array([6.32455532, 2.25      , 4.60977223]),
  array([4.12310563, 3.01039864, 1.11803399]),
  array([4.24264069, 1.25      , 4.5       ]),
  array([3.60555128, 4.06970515, 0.5       ]),
  array([4.47213595, 0.25      , 3.64005494]),
  array([2.23606798, 2.01556444, 2.6925824 ])],
 array([0, 0, 2, 2, 1, 2, 1, 2, 1, 1]),
 array([[2.  , 5.  ],
        [5.75, 3.  ],
        [5.  , 6.5 ]]))